/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.icet.sms.view;

import com.icet.sms.controller.StudentController;
import com.icet.sms.model.Student;
import javax.swing.table.DefaultTableModel;
import com.icet.sms.db.List;

/**
 *
 * @author nirot
 */
public class ViewStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentForm
     */
    public ViewStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        prfBesButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dbmsbestButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Name", "PRF", "DBMS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(studentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 950, 261));

        prfBesButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prfBesButton.setText("Best in PRF");
        prfBesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfBesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(prfBesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 122, 145, 45));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Student Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 988, -1));

        dbmsbestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbmsbestButton.setText("Best in DBMS");
        dbmsbestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbmsbestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dbmsbestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 122, 145, 45));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Print");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 90, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icet/sms/view/32925.png"))); // NOI18N
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 500, 420));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icet/sms/view/32925.png"))); // NOI18N
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 470, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prfBesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfBesButtonActionPerformed
        
        Student[] studentArray=(Student[]) StudentController.getAllStudent();
        
        for(int i=studentArray.length-1; i>0; i--){
            for(int j=0; j<studentArray.length-1; j++){
                if(studentArray[j].getPrf()<studentArray[j+1].getPrf()){
                    Student temp=studentArray[j+1];
                    studentArray[j+1]= studentArray[j];
                    studentArray[j]=temp;
                }
            }
        }
        
        DefaultTableModel dtm=(DefaultTableModel) studentTable.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < studentArray.length; i++) {
            
            Student st=studentArray[i];
            Object[] rowData={st.getId(),st.getName(),st.getPrf(),st.getDbms()};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_prfBesButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dbmsbestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbmsbestButtonActionPerformed
        Student[] studentArray=StudentController.getAllStudent();
        
        for(int i=studentArray.length-1; i>0; i--){
            for(int j=0; j<studentArray.length-1; j++){
                if(studentArray[j].getDbms()<studentArray[j+1].getDbms()){
                    Student temp=studentArray[j+1];
                    studentArray[j+1]= studentArray[j];
                    studentArray[j]=temp;
                }
            }
        }
        
        DefaultTableModel dtm=(DefaultTableModel) studentTable.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < studentArray.length; i++) {
            Student st=studentArray[i];
            Object[] rowData={st.getId(),st.getName(),st.getPrf(),st.getDbms()};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_dbmsbestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbmsbestButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prfBesButton;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
